### ISSUE TITLE
[Question] Regarding xml stream parser

### ISSUE THREAD

**Issue by tuananh** [silviucpp/erlxml#1]
Hi,

Could you give an example on how to use the xml stream parser (https://github.com/silviucpp/erlxml/tree/master/c_src)?

Thank you in advance.

**Comment by silviucpp** [comment]
Hello,

The code can't be use standalone. Is part of erlxml which is an erlang xml parser for streams based on pugixml.

If you want to use it in a c application you can get inspired from https://github.com/silviucpp/erlxml/blob/master/c_src/xmlstreamparser.h .

You are calling FeedData with parts of your stream and time to time callbacks provided in constutor are called with the stanzas found (pugi::xml_document)

Silviu

**Comment by tuananh** [comment]
Thank you. Lemme digest this.
